-- Execute no novo projeto: SQL Editor → New query → Run
-- Schema baseado na estrutura real do projeto antigo

-- ── properties ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS properties (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    timestamptz DEFAULT now(),
  title         text,
  type          text,
  price         numeric,
  saleprice     numeric,
  rentalprice   numeric,
  contract      text,
  status        text DEFAULT 'Disponível',
  area          numeric,
  rooms         integer,
  bathrooms     integer,
  garage        integer,
  address       text,
  description   text,
  image         text,
  images        text,
  video         text,
  featured      boolean DEFAULT false,
  owner_id      text,
  price_type    text DEFAULT 'fixo',
  rental_price  numeric DEFAULT 0,
  caucao        boolean DEFAULT false,
  fiador        boolean DEFAULT false,
  contact_agent text
);

-- ── blog_posts ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS blog_posts (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now(),
  title       text,
  excerpt     text,
  content     text,
  cover_image text,
  category    text,
  author      text,
  status      text DEFAULT 'draft',
  slug        text UNIQUE
);

-- ── partners ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS partners (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now(),
  name        text NOT NULL,
  category    text,
  description text,
  tip_content text,
  logo_url    text,
  website_url text,
  whatsapp    text,
  status      text DEFAULT 'active'
);

-- ── leads ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS leads (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz DEFAULT now(),
  name        text,
  phone       text,
  interest    text,
  status      text
);

-- ── people ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS people (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  timestamptz DEFAULT now(),
  name        text,
  phone       text,
  email       text,
  type        text,
  notes       text,
  updated_at  timestamptz DEFAULT now()
);

-- ── profiles ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS profiles (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  timestamptz DEFAULT now(),
  email       text,
  role        text DEFAULT 'client'
);

-- ── dashboard_config ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS dashboard_config (
  id               text PRIMARY KEY DEFAULT 'default',
  updated_at       timestamptz DEFAULT now(),
  meta_venda       numeric DEFAULT 0,
  meta_locacao     numeric DEFAULT 0,
  vendas_venda     numeric DEFAULT 0,
  vendas_locacao   numeric DEFAULT 0,
  leads_venda      numeric DEFAULT 0,
  leads_locacao    numeric DEFAULT 0,
  comissoes_venda  numeric DEFAULT 0,
  comissoes_locacao numeric DEFAULT 0,
  funil_venda      text DEFAULT '[0,0,0,0]',
  funil_locacao    text DEFAULT '[0,0,0,0]'
);

-- ── site_settings ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS site_settings (
  id            text PRIMARY KEY DEFAULT 'default',
  updated_at    timestamptz DEFAULT now(),
  whatsapp      text,
  telegram      text,
  socials       text,
  primary_color text DEFAULT '#166b9c',
  system_prompt text,
  gemini_key    text,
  groq_key      text
);

-- ── whatsapp_matches ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS whatsapp_matches (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at          timestamptz DEFAULT now(),
  sender_name         text,
  sender_phone        text,
  group_name          text,
  message             text,
  intent              jsonb,
  matched_properties  jsonb,
  read                boolean DEFAULT false
);

-- ── RLS ───────────────────────────────────────────────────────────────────────
ALTER TABLE properties       ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog_posts       ENABLE ROW LEVEL SECURITY;
ALTER TABLE partners         ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads            ENABLE ROW LEVEL SECURITY;
ALTER TABLE people           ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles         ENABLE ROW LEVEL SECURITY;
ALTER TABLE dashboard_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings    ENABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp_matches ENABLE ROW LEVEL SECURITY;

-- Leitura pública (site público)
CREATE POLICY "public read properties"    ON properties    FOR SELECT TO anon USING (true);
CREATE POLICY "public read blog_posts"    ON blog_posts    FOR SELECT TO anon USING (true);
CREATE POLICY "public read partners"      ON partners      FOR SELECT TO anon USING (status = 'active');
CREATE POLICY "public read site_settings" ON site_settings FOR SELECT TO anon USING (true);

-- Acesso total para autenticados (admin)
CREATE POLICY "auth full properties"       ON properties       FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth full blog_posts"       ON blog_posts       FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth full partners"         ON partners         FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth full leads"            ON leads            FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth full people"           ON people           FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth full profiles"         ON profiles         FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth full dashboard_config" ON dashboard_config FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth full site_settings"    ON site_settings    FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth full whatsapp_matches" ON whatsapp_matches FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Service role (whatsapp-monitor)
CREATE POLICY "service full whatsapp_matches" ON whatsapp_matches FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "service full site_settings"    ON site_settings    FOR ALL TO service_role USING (true) WITH CHECK (true);
