-- Parceiros: dicas de produtos e serviços de parceiros (financiamento, decoração, mudança, seguros, etc.)
create table if not exists public.partners (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now(),
  name         text not null,
  category     text,
  description  text,
  tip_content  text,
  logo_url     text,
  website_url  text,
  whatsapp     text,
  status       text default 'active'
);

alter table public.partners enable row level security;

create policy "public read partners" on public.partners
  for select to anon using (status = 'active');

create policy "auth full partners" on public.partners
  for all to authenticated using (true) with check (true);
